# Generated by Django 5.2.8 on 2025-11-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='uid',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='Уникальный идентификатор 1С'),
        ),
    ]
