"""change ticket model

Revision ID: 2e93a765979d
Revises: 147b20e1f2ac
Create Date: 2023-12-14 19:11:26.320239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e93a765979d'
down_revision = '147b20e1f2ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('Справка 2-НДФЛ', 'Справка с места работы', 'Справока по использованным отпускам'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
