"""empty message

Revision ID: 77cf2f60daf9
Revises: fc6ef84b714c
Create Date: 2023-12-19 12:09:10.571179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77cf2f60daf9'
down_revision = 'fc6ef84b714c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=35),
               type_=sa.Enum('Справка 2-НДФЛ', 'Справка с места работы', 'Справка по использованным отпускам'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('Справка 2-НДФЛ', 'Справка с места работы', 'Справка по использованным отпускам'),
               type_=sa.VARCHAR(length=35),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=True)

    # ### end Alembic commands ###
