"""empty message

Revision ID: 84baf52017f5
Revises: 77cf2f60daf9
Create Date: 2023-12-19 12:27:45.793580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84baf52017f5'
down_revision = '77cf2f60daf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###
